#!/usr/bin/env python3
"""
Bundle Adjustment Panorama Stitcher

Implements the techniques from Brown & Lowe's seminal paper:
"Automatic Panoramic Image Stitching using Invariant Features" (2007)

Key improvements over simple sensor-based stitching:
1. SIFT feature detection with k-NN matching and Lowe's ratio test
2. RANSAC homography estimation with probabilistic verification
3. Bundle adjustment to jointly optimize ALL camera parameters
4. Gain compensation for exposure normalization
5. Multi-band blending using Laplacian pyramids

This should dramatically improve stitching quality to near 1.0.
"""

import cv2
import numpy as np
import math
import sys
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass
from scipy.optimize import least_squares
from scipy.ndimage import gaussian_filter


# =============================================================================
# DATA STRUCTURES
# =============================================================================

@dataclass
class CameraParams:
    """Camera parameters: 3 rotation angles + focal length"""
    theta1: float  # Rotation around X
    theta2: float  # Rotation around Y  
    theta3: float  # Rotation around Z
    focal: float   # Focal length


@dataclass 
class FeatureMatch:
    """A verified match between two images"""
    img_i: int
    img_j: int
    pts_i: np.ndarray  # Nx2 points in image i
    pts_j: np.ndarray  # Nx2 points in image j
    inlier_mask: np.ndarray
    num_inliers: int


# =============================================================================
# SIFT FEATURE DETECTION AND MATCHING (Section 2 of paper)
# =============================================================================

class SIFTMatcher:
    """
    SIFT feature detection and matching with Lowe's ratio test.
    
    From the paper:
    "SIFT features are invariant under rotation and scale changes,
    our system can handle images with varying orientation and zoom."
    """
    
    def __init__(self, n_features: int = 2000, ratio_threshold: float = 0.75):
        self.n_features = n_features
        self.ratio_threshold = ratio_threshold
        
        # Create SIFT detector
        self.sift = cv2.SIFT_create(
            nfeatures=n_features,
            contrastThreshold=0.04,
            edgeThreshold=10
        )
        
        # FLANN matcher for efficient k-NN search (Section 2 of paper)
        # "k nearest neighbours in feature space (we use k=4)"
        index_params = dict(algorithm=1, trees=5)  # FLANN_INDEX_KDTREE
        search_params = dict(checks=50)
        self.flann = cv2.FlannBasedMatcher(index_params, search_params)
    
    def detect_and_describe(self, image: np.ndarray) -> Tuple[List[cv2.KeyPoint], np.ndarray]:
        """Detect SIFT keypoints and compute descriptors"""
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        keypoints, descriptors = self.sift.detectAndCompute(gray, None)
        return keypoints, descriptors
    
    def match_images(
        self, 
        desc1: np.ndarray, 
        desc2: np.ndarray,
        kp1: List[cv2.KeyPoint],
        kp2: List[cv2.KeyPoint]
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Match features using Lowe's ratio test.
        
        From paper: "Each feature is matched to its k nearest neighbours
        in feature space. A match is accepted if the ratio of distances
        to the first and second nearest neighbours is less than 0.75."
        """
        if desc1 is None or desc2 is None or len(desc1) < 2 or len(desc2) < 2:
            return np.array([]), np.array([])
        
        # k-NN matching
        matches = self.flann.knnMatch(desc1, desc2, k=2)
        
        # Ratio test
        good_pts1 = []
        good_pts2 = []
        
        for match in matches:
            if len(match) == 2:
                m, n = match
                if m.distance < self.ratio_threshold * n.distance:
                    good_pts1.append(kp1[m.queryIdx].pt)
                    good_pts2.append(kp2[m.trainIdx].pt)
        
        return np.array(good_pts1), np.array(good_pts2)


# =============================================================================
# RANSAC HOMOGRAPHY WITH PROBABILISTIC VERIFICATION (Section 3 of paper)
# =============================================================================

class RANSACVerifier:
    """
    RANSAC homography estimation with probabilistic match verification.
    
    From paper Section 3.2:
    "We compare the probabilities that this set of inliers/outliers
    was generated by a correct image match or by a false image match."
    """
    
    def __init__(
        self, 
        ransac_threshold: float = 4.0,
        n_trials: int = 500,
        p_inlier_correct: float = 0.6,  # p1 in paper
        p_inlier_false: float = 0.1,    # p0 in paper
        p_min: float = 0.999            # Minimum match probability
    ):
        self.ransac_threshold = ransac_threshold
        self.n_trials = n_trials
        self.p1 = p_inlier_correct
        self.p0 = p_inlier_false
        self.p_min = p_min
    
    def verify_match(
        self, 
        pts1: np.ndarray, 
        pts2: np.ndarray,
        min_inliers: int = 8
    ) -> Tuple[Optional[np.ndarray], np.ndarray, float]:
        """
        Estimate homography with RANSAC and verify using probabilistic model.
        
        Returns:
            H: 3x3 homography matrix (or None if verification failed)
            mask: Inlier mask
            probability: Probability this is a correct match
        """
        if len(pts1) < 4:
            return None, np.array([]), 0.0
        
        # RANSAC homography estimation
        H, mask = cv2.findHomography(
            pts1.reshape(-1, 1, 2),
            pts2.reshape(-1, 1, 2),
            cv2.RANSAC,
            self.ransac_threshold
        )
        
        if H is None or mask is None:
            return None, np.array([]), 0.0
        
        mask = mask.ravel().astype(bool)
        n_inliers = np.sum(mask)
        n_features = len(mask)
        
        if n_inliers < min_inliers:
            return None, mask, 0.0
        
        # Probabilistic verification (Eq. 10-12 from paper)
        # P(m=1|inliers) using Bayes' rule
        p_correct = self._compute_match_probability(n_inliers, n_features)
        
        if p_correct < self.p_min:
            return None, mask, p_correct
        
        return H, mask, p_correct
    
    def _compute_match_probability(self, n_inliers: int, n_features: int) -> float:
        """
        Compute probability of correct match using Bayesian verification.
        
        From paper Eq. 10-12:
        P(m=1|f) = P(f|m=1)P(m=1) / P(f)
        """
        if n_features == 0:
            return 0.0
        
        # Prior probabilities (assume equal prior)
        p_m1 = 0.5  # Prior that match is correct
        
        # Likelihood of observing n_inliers given correct/false match
        # Using binomial distribution approximation
        # P(n_i inliers | correct match) ~ B(n_i; n_f, p1)
        # P(n_i inliers | false match) ~ B(n_i; n_f, p0)
        
        # Log-likelihood ratio (more numerically stable)
        log_ratio = n_inliers * np.log(self.p1 / self.p0 + 1e-10)
        log_ratio += (n_features - n_inliers) * np.log((1 - self.p1) / (1 - self.p0) + 1e-10)
        
        # Convert to probability via sigmoid
        prob = 1.0 / (1.0 + np.exp(-log_ratio))
        
        return prob


# =============================================================================
# BUNDLE ADJUSTMENT (Section 4 of paper)
# =============================================================================

class BundleAdjuster:
    """
    Bundle adjustment to jointly optimize all camera parameters.
    
    From paper Section 4:
    "We use bundle adjustment to solve for all of the camera parameters
    jointly. This is an essential step as concatenation of pairwise
    homographies would cause accumulated errors."
    
    Minimizes the robustified sum squared projection error (Eq. 16):
    e = sum_i sum_j sum_k h(r_ij^k)
    
    where r_ij^k is the residual between projected and observed feature location.
    """
    
    def __init__(
        self,
        huber_sigma: float = 2.0,  # sigma in Huber robust function
        max_iterations: int = 100
    ):
        self.sigma = huber_sigma
        self.max_iterations = max_iterations
    
    def optimize(
        self,
        n_images: int,
        matches: List[FeatureMatch],
        initial_params: List[CameraParams],
        image_sizes: List[Tuple[int, int]]
    ) -> List[CameraParams]:
        """
        Run bundle adjustment optimization.
        
        Args:
            n_images: Number of images
            matches: List of verified feature matches
            initial_params: Initial camera parameters from sensor data
            image_sizes: (width, height) for each image
            
        Returns:
            Optimized camera parameters
        """
        if not matches:
            return initial_params
        
        print(f"[BundleAdjust] Optimizing {n_images} cameras with {len(matches)} image pairs", file=sys.stderr)
        
        # Pack parameters into vector: [theta1, theta2, theta3, focal] * n_images
        x0 = self._pack_params(initial_params)
        
        # Run Levenberg-Marquardt optimization
        result = least_squares(
            self._compute_residuals,
            x0,
            args=(matches, image_sizes),
            method='lm',
            max_nfev=self.max_iterations * len(x0),
            verbose=0
        )
        
        if result.success:
            print(f"[BundleAdjust] Converged after {result.nfev} evaluations", file=sys.stderr)
        else:
            print(f"[BundleAdjust] Warning: {result.message}", file=sys.stderr)
        
        return self._unpack_params(result.x, n_images)
    
    def _pack_params(self, params: List[CameraParams]) -> np.ndarray:
        """Pack camera parameters into flat vector"""
        x = []
        for p in params:
            x.extend([p.theta1, p.theta2, p.theta3, p.focal])
        return np.array(x)
    
    def _unpack_params(self, x: np.ndarray, n: int) -> List[CameraParams]:
        """Unpack flat vector into camera parameters"""
        params = []
        for i in range(n):
            idx = i * 4
            params.append(CameraParams(
                theta1=x[idx],
                theta2=x[idx + 1],
                theta3=x[idx + 2],
                focal=x[idx + 3]
            ))
        return params
    
    def _compute_residuals(
        self,
        x: np.ndarray,
        matches: List[FeatureMatch],
        image_sizes: List[Tuple[int, int]]
    ) -> np.ndarray:
        """
        Compute all residuals for bundle adjustment.
        
        For each feature match (u_i, u_j), compute:
        r = u_i - proj(R_i @ R_j^T @ unproj(u_j))
        
        Apply Huber robust function to downweight outliers.
        
        CRITICAL FIX: Pre-compute expected residual count to ensure
        consistent array size across iterations (fixes scipy error).
        """
        n = len(image_sizes)
        params = self._unpack_params(x, n)
        
        # Pre-allocate fixed-size array based on total possible residuals
        # Each inlier can produce 2 residuals (dx, dy)
        total_inliers = sum(match.num_inliers for match in matches)
        residuals = np.zeros(total_inliers * 2)
        residual_idx = 0
        
        for match in matches:
            i, j = match.img_i, match.img_j
            w_i, h_i = image_sizes[i]
            w_j, h_j = image_sizes[j]
            
            # Get rotation matrices
            R_i = self._params_to_rotation(params[i])
            R_j = self._params_to_rotation(params[j])
            f_i = params[i].focal
            f_j = params[j].focal
            
            # Relative rotation
            R_rel = R_i @ R_j.T
            
            # For each inlier point pair
            for k in range(len(match.pts_i)):
                if not match.inlier_mask[k]:
                    continue
                
                pt_i = match.pts_i[k]
                pt_j = match.pts_j[k]
                
                # Unproject point j to 3D ray
                ray_j = np.array([
                    (pt_j[0] - w_j / 2) / f_j,
                    (pt_j[1] - h_j / 2) / f_j,
                    1.0
                ])
                ray_j = ray_j / np.linalg.norm(ray_j)
                
                # Transform to image i frame
                ray_i = R_rel @ ray_j
                
                # Always compute residual (even if behind camera)
                # This ensures consistent array size
                if ray_i[2] > 0.01:
                    proj_x = f_i * ray_i[0] / ray_i[2] + w_i / 2
                    proj_y = f_i * ray_i[1] / ray_i[2] + h_i / 2
                    
                    # Residual
                    dx = pt_i[0] - proj_x
                    dy = pt_i[1] - proj_y
                    
                    # Apply Huber robust function (Eq. 17 from paper)
                    r = np.sqrt(dx**2 + dy**2)
                    if r < self.sigma:
                        residuals[residual_idx] = dx
                        residuals[residual_idx + 1] = dy
                    else:
                        # Robust: sqrt(2*sigma*|r| - sigma^2)
                        scale = np.sqrt(2 * self.sigma / (r + 1e-6))
                        residuals[residual_idx] = dx * scale
                        residuals[residual_idx + 1] = dy * scale
                else:
                    # Behind camera: assign large residual to downweight
                    residuals[residual_idx] = 100.0
                    residuals[residual_idx + 1] = 100.0
                
                residual_idx += 2
        
        return residuals
    
    def _params_to_rotation(self, params: CameraParams) -> np.ndarray:
        """Convert camera parameters to rotation matrix using exponential map (Eq. 3)"""
        theta = np.array([params.theta1, params.theta2, params.theta3])
        
        # Rodrigues formula
        angle = np.linalg.norm(theta)
        if angle < 1e-8:
            return np.eye(3)
        
        axis = theta / angle
        K = np.array([
            [0, -axis[2], axis[1]],
            [axis[2], 0, -axis[0]],
            [-axis[1], axis[0], 0]
        ])
        
        R = np.eye(3) + np.sin(angle) * K + (1 - np.cos(angle)) * (K @ K)
        return R


# =============================================================================
# GAIN COMPENSATION (Section 6 of paper)
# =============================================================================

class GainCompensator:
    """
    Compute per-image gain factors for exposure normalization.
    
    From paper Section 6:
    "The error function is the sum of gain normalised intensity
    errors for all overlapping pixels."
    
    Minimizes: e = sum_ij sum_u (g_i*I_i(u) - g_j*I_j(u))^2 / sigma_N^2
                   + sum_i (1 - g_i)^2 / sigma_g^2
    """
    
    def __init__(self, sigma_n: float = 10.0, sigma_g: float = 0.1):
        self.sigma_n = sigma_n
        self.sigma_g = sigma_g
    
    def compute_gains(
        self,
        images: List[np.ndarray],
        matches: List[FeatureMatch]
    ) -> np.ndarray:
        """
        Compute optimal gains using closed-form solution (Eq. 29 from paper).
        
        The quadratic objective can be solved by setting derivative to 0.
        """
        n = len(images)
        
        if n <= 1 or not matches:
            return np.ones(n)
        
        # Build linear system: Ag = b
        # A_ii = sum_j N_ij / sigma_N^2 + 1 / sigma_g^2
        # A_ij = -N_ij * mean(I_i) * mean(I_j) / (mean(I_i)^2 * sigma_N^2)  
        # b_i = 1 / sigma_g^2
        
        A = np.zeros((n, n))
        b = np.ones(n) / (self.sigma_g ** 2)
        
        # Compute mean intensities
        means = []
        for img in images:
            means.append(np.mean(img.astype(np.float32)))
        
        # Add constraints from each match
        for match in matches:
            i, j = match.img_i, match.img_j
            n_overlap = match.num_inliers * 100  # Approximate overlap size
            
            if means[i] > 0 and means[j] > 0:
                # Intensity ratio
                ratio = means[i] / means[j]
                
                # Add to matrix
                coef = n_overlap / (self.sigma_n ** 2)
                A[i, i] += coef
                A[j, j] += coef * ratio ** 2
                A[i, j] -= coef * ratio
                A[j, i] -= coef * ratio
        
        # Add regularization term (keep gains near 1)
        for i in range(n):
            A[i, i] += 1 / (self.sigma_g ** 2)
        
        # Solve
        try:
            gains = np.linalg.solve(A, b)
            # Normalize so mean = 1
            gains = gains / np.mean(gains)
            # Clamp to reasonable range
            gains = np.clip(gains, 0.5, 2.0)
        except np.linalg.LinAlgError:
            gains = np.ones(n)
        
        return gains
    
    def apply_gains(
        self,
        images: List[np.ndarray],
        gains: np.ndarray
    ) -> List[np.ndarray]:
        """Apply computed gains to images"""
        result = []
        for img, g in zip(images, gains):
            adjusted = np.clip(img.astype(np.float32) * g, 0, 255).astype(np.uint8)
            result.append(adjusted)
        return result


# =============================================================================
# MULTI-BAND BLENDING (Section 7 of paper)
# =============================================================================

class MultiBandBlender:
    """
    Multi-band blending using Laplacian pyramids.
    
    From paper Section 7:
    "The idea behind multi-band blending is to blend low frequencies
    over a large spatial range, and high frequencies over a short range."
    
    This preserves fine details while smoothly blending exposure differences.
    """
    
    def __init__(self, n_bands: int = 5, sigma: float = 5.0):
        self.n_bands = n_bands
        self.sigma = sigma
    
    def blend_panorama(
        self,
        projections: List[Tuple[np.ndarray, np.ndarray]],
        output_size: Tuple[int, int]
    ) -> np.ndarray:
        """
        Blend multiple projected images using multi-band blending.
        
        Args:
            projections: List of (color_image, weight_mask) tuples
            output_size: (height, width) of output
            
        Returns:
            Blended panorama
        """
        h, w = output_size
        
        # Build weight maps for each image (Eq. 31 from paper)
        # W_max = 1 where this image has highest weight, 0 elsewhere
        combined_weights = np.zeros((h, w), dtype=np.float32)
        for _, weight in projections:
            combined_weights = np.maximum(combined_weights, weight)
        
        max_weight_maps = []
        for _, weight in projections:
            max_map = (weight >= combined_weights - 1e-6).astype(np.float32)
            max_weight_maps.append(max_map)
        
        # Build Laplacian pyramids for each image
        laplacian_pyramids = []
        weight_pyramids = []
        
        for (color, _), w_max in zip(projections, max_weight_maps):
            lap_pyr = self._build_laplacian_pyramid(color.astype(np.float32))
            w_pyr = self._build_gaussian_pyramid(w_max)
            laplacian_pyramids.append(lap_pyr)
            weight_pyramids.append(w_pyr)
        
        # Blend each band (Eq. 38 from paper)
        blended_pyramid = []
        
        for level in range(self.n_bands):
            blended_level = np.zeros_like(laplacian_pyramids[0][level])
            weight_sum = np.zeros(laplacian_pyramids[0][level].shape[:2], dtype=np.float32)
            
            for lap_pyr, w_pyr in zip(laplacian_pyramids, weight_pyramids):
                # Expand weight to match Laplacian shape if needed
                w = w_pyr[level]
                if len(blended_level.shape) == 3:
                    w = w[:, :, np.newaxis]
                
                blended_level += lap_pyr[level] * w
                weight_sum += w_pyr[level]
            
            # Normalize by total weight
            weight_sum = np.maximum(weight_sum, 1e-6)
            if len(blended_level.shape) == 3:
                weight_sum = weight_sum[:, :, np.newaxis]
            blended_level /= weight_sum
            
            blended_pyramid.append(blended_level)
        
        # Collapse pyramid
        result = self._collapse_laplacian_pyramid(blended_pyramid)
        
        return np.clip(result, 0, 255).astype(np.uint8)
    
    def _build_gaussian_pyramid(self, image: np.ndarray) -> List[np.ndarray]:
        """Build Gaussian pyramid"""
        pyramid = [image.astype(np.float32)]
        
        for _ in range(self.n_bands - 1):
            # Blur and downsample
            blurred = gaussian_filter(pyramid[-1], self.sigma)
            downsampled = blurred[::2, ::2] if len(blurred.shape) == 2 else blurred[::2, ::2, :]
            pyramid.append(downsampled)
        
        return pyramid
    
    def _build_laplacian_pyramid(self, image: np.ndarray) -> List[np.ndarray]:
        """Build Laplacian pyramid (Eq. 32-33 from paper)"""
        gaussian = self._build_gaussian_pyramid(image)
        laplacian = []
        
        for i in range(len(gaussian) - 1):
            # Upsample next level
            if len(gaussian[i].shape) == 2:
                h, w = gaussian[i].shape
            else:
                h, w = gaussian[i].shape[:2]
            
            upsampled = cv2.resize(gaussian[i + 1], (w, h), interpolation=cv2.INTER_LINEAR)
            
            # Difference = high frequencies at this level
            laplacian.append(gaussian[i] - upsampled)
        
        # Coarsest level is low-frequency residual
        laplacian.append(gaussian[-1])
        
        return laplacian
    
    def _collapse_laplacian_pyramid(self, pyramid: List[np.ndarray]) -> np.ndarray:
        """Reconstruct image from Laplacian pyramid"""
        result = pyramid[-1]
        
        for i in range(len(pyramid) - 2, -1, -1):
            # Upsample
            if len(pyramid[i].shape) == 2:
                h, w = pyramid[i].shape
            else:
                h, w = pyramid[i].shape[:2]
            
            result = cv2.resize(result, (w, h), interpolation=cv2.INTER_LINEAR)
            result = result + pyramid[i]
        
        return result


# =============================================================================
# MAIN STITCHER
# =============================================================================

class BundleAdjustmentStitcher:
    """
    Complete panorama stitcher implementing Brown & Lowe 2007.
    
    Pipeline:
    1. Extract SIFT features from all images
    2. Match features between candidate pairs
    3. Verify matches with RANSAC + probabilistic model
    4. Build image connectivity graph
    5. Bundle adjustment to optimize all cameras jointly
    6. Gain compensation for exposure normalization
    7. Project to equirectangular
    8. Multi-band blending
    """
    
    def __init__(
        self,
        output_width: int = 4096,
        output_height: int = 2048,
        fov_h: float = 75.0,
        fov_v: float = 55.0
    ):
        self.output_width = output_width
        self.output_height = output_height
        self.fov_h = fov_h
        self.fov_v = fov_v
        
        self.matcher = SIFTMatcher()
        self.verifier = RANSACVerifier()
        self.bundle_adjuster = BundleAdjuster()
        self.gain_compensator = GainCompensator()
        self.blender = MultiBandBlender()
    
    def stitch(
        self,
        photos: List[Dict],
        images: List[np.ndarray],
        depth_maps: List[Optional[np.ndarray]] = None
    ) -> Tuple[np.ndarray, Optional[np.ndarray], Dict]:
        """
        Main stitching function.
        
        Returns:
            panorama: Stitched equirectangular image
            depth_panorama: Stitched depth (if available)
            stats: Processing statistics
        """
        n = len(images)
        print(f"[BundleStitch] Processing {n} images...", file=sys.stderr)
        
        # Step 1: Extract features
        print("[BundleStitch] Step 1: Extracting SIFT features...", file=sys.stderr)
        features = []
        for i, img in enumerate(images):
            kp, desc = self.matcher.detect_and_describe(img)
            features.append((kp, desc))
            print(f"  Image {i+1}: {len(kp)} keypoints", file=sys.stderr)
        
        # Step 2: Match candidate pairs
        print("[BundleStitch] Step 2: Matching image pairs...", file=sys.stderr)
        matches = self._find_matches(photos, images, features)
        print(f"  Found {len(matches)} verified pairs", file=sys.stderr)
        
        # Step 3: Initialize camera parameters from sensors
        print("[BundleStitch] Step 3: Initializing cameras...", file=sys.stderr)
        initial_params = self._init_cameras(photos, images)
        
        # Step 4: Bundle adjustment
        print("[BundleStitch] Step 4: Bundle adjustment...", file=sys.stderr)
        image_sizes = [(img.shape[1], img.shape[0]) for img in images]
        
        if matches:
            optimized_params = self.bundle_adjuster.optimize(
                n, matches, initial_params, image_sizes
            )
        else:
            print("  Warning: No verified matches, using sensor positions only", file=sys.stderr)
            optimized_params = initial_params
        
        # Step 5: Gain compensation
        print("[BundleStitch] Step 5: Gain compensation...", file=sys.stderr)
        gains = self.gain_compensator.compute_gains(images, matches)
        images_corrected = self.gain_compensator.apply_gains(images, gains)
        print(f"  Gains: {[f'{g:.2f}' for g in gains]}", file=sys.stderr)
        
        # Step 6: Project and blend
        print("[BundleStitch] Step 6: Projecting and blending...", file=sys.stderr)
        panorama = self._project_and_blend(images_corrected, optimized_params)
        
        # Step 7: Fill gaps
        print("[BundleStitch] Step 7: Filling gaps...", file=sys.stderr)
        panorama = self._fill_gaps(panorama)
        
        # Compute quality metrics
        stats = {
            'photoCount': n,
            'matchedPairs': len(matches),
            'totalInliers': sum(m.num_inliers for m in matches),
            'gains': gains.tolist(),
            'method': 'bundle_adjustment',
            'blending': 'multi_band'
        }
        
        print("[BundleStitch] Complete!", file=sys.stderr)
        return panorama, None, stats
    
    def _find_matches(
        self,
        photos: List[Dict],
        images: List[np.ndarray],
        features: List[Tuple]
    ) -> List[FeatureMatch]:
        """Find and verify all image matches"""
        n = len(images)
        matches = []
        
        # Find candidate pairs by angular proximity
        for i in range(n):
            az_i = photos[i].get('azimuth', 0)
            el_i = photos[i].get('elevation', 0)
            
            for j in range(i + 1, n):
                az_j = photos[j].get('azimuth', 0)
                el_j = photos[j].get('elevation', 0)
                
                # Angular distance
                az_diff = abs(((az_i - az_j + 180) % 360) - 180)
                el_diff = abs(el_i - el_j)
                
                # Skip if too far apart (no expected overlap)
                if az_diff > 50 or el_diff > 50:
                    continue
                
                # Match features
                kp_i, desc_i = features[i]
                kp_j, desc_j = features[j]
                
                pts_i, pts_j = self.matcher.match_images(desc_i, desc_j, kp_i, kp_j)
                
                if len(pts_i) < 10:
                    continue
                
                # Verify with RANSAC
                H, mask, prob = self.verifier.verify_match(pts_i, pts_j)
                
                if H is not None:
                    match = FeatureMatch(
                        img_i=i,
                        img_j=j,
                        pts_i=pts_i,
                        pts_j=pts_j,
                        inlier_mask=mask,
                        num_inliers=int(np.sum(mask))
                    )
                    matches.append(match)
                    print(f"  Pair ({i+1}, {j+1}): {match.num_inliers} inliers, p={prob:.3f}", file=sys.stderr)
        
        return matches
    
    def _init_cameras(
        self,
        photos: List[Dict],
        images: List[np.ndarray]
    ) -> List[CameraParams]:
        """Initialize camera parameters from sensor data"""
        params = []
        
        for i, (photo, img) in enumerate(zip(photos, images)):
            az = math.radians(photo.get('azimuth', 0))
            el = math.radians(photo.get('elevation', 0))
            
            # Convert to rotation vector
            # theta2 = azimuth (rotation around Y)
            # theta1 = elevation (rotation around X)
            theta1 = -el
            theta2 = az
            theta3 = 0.0
            
            # Estimate focal length from FOV
            w = img.shape[1]
            focal = w / (2 * math.tan(math.radians(self.fov_h / 2)))
            
            params.append(CameraParams(
                theta1=theta1,
                theta2=theta2,
                theta3=theta3,
                focal=focal
            ))
        
        return params
    
    def _params_to_rotation(self, params: CameraParams) -> np.ndarray:
        """Convert camera parameters to rotation matrix"""
        theta = np.array([params.theta1, params.theta2, params.theta3])
        
        angle = np.linalg.norm(theta)
        if angle < 1e-8:
            return np.eye(3)
        
        axis = theta / angle
        K = np.array([
            [0, -axis[2], axis[1]],
            [axis[2], 0, -axis[0]],
            [-axis[1], axis[0], 0]
        ])
        
        return np.eye(3) + np.sin(angle) * K + (1 - np.cos(angle)) * (K @ K)
    
    def _project_and_blend(
        self,
        images: List[np.ndarray],
        params: List[CameraParams]
    ) -> np.ndarray:
        """Project images and blend using multi-band"""
        h, w = self.output_height, self.output_width
        
        # Project each image
        projections = []
        
        for i, (img, p) in enumerate(zip(images, params)):
            print(f"  Projecting image {i+1}...", file=sys.stderr)
            
            R = self._params_to_rotation(p)
            projected, weight = self._project_single(img, R, p.focal)
            projections.append((projected, weight))
        
        # Multi-band blend
        print("  Multi-band blending...", file=sys.stderr)
        panorama = self.blender.blend_panorama(projections, (h, w))
        
        return panorama
    
    def _project_single(
        self,
        img: np.ndarray,
        R: np.ndarray,
        focal: float
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Project single image to equirectangular"""
        h_out, w_out = self.output_height, self.output_width
        h_in, w_in = img.shape[:2]
        
        projected = np.zeros((h_out, w_out, 3), dtype=np.float32)
        weight = np.zeros((h_out, w_out), dtype=np.float32)
        
        cx, cy = w_in / 2, h_in / 2
        R_inv = R.T
        
        for v in range(h_out):
            phi = (0.5 - v / h_out) * math.pi
            
            for u in range(w_out):
                theta = (u / w_out - 0.5) * 2 * math.pi
                
                # 3D direction
                world_dir = np.array([
                    math.cos(phi) * math.sin(theta),
                    math.sin(phi),
                    math.cos(phi) * math.cos(theta)
                ])
                
                # Transform to camera frame
                cam_dir = R_inv @ world_dir
                
                if cam_dir[2] <= 0.01:
                    continue
                
                # Project
                img_x = focal * (cam_dir[0] / cam_dir[2]) + cx
                img_y = focal * (cam_dir[1] / cam_dir[2]) + cy
                
                if 0 <= img_x < w_in - 1 and 0 <= img_y < h_in - 1:
                    # Bilinear interpolation
                    x0, y0 = int(img_x), int(img_y)
                    dx, dy = img_x - x0, img_y - y0
                    
                    color = (
                        img[y0, x0] * (1-dx) * (1-dy) +
                        img[y0, min(x0+1, w_in-1)] * dx * (1-dy) +
                        img[min(y0+1, h_in-1), x0] * (1-dx) * dy +
                        img[min(y0+1, h_in-1), min(x0+1, w_in-1)] * dx * dy
                    )
                    
                    projected[v, u] = color
                    
                    # Weight with smooth falloff
                    dist_x = abs(img_x - cx) / (w_in / 2)
                    dist_y = abs(img_y - cy) / (h_in / 2)
                    dist = math.sqrt(dist_x**2 + dist_y**2)
                    weight[v, u] = max(0, 1 - dist**2)
        
        return projected, weight
    
    def _fill_gaps(self, panorama: np.ndarray) -> np.ndarray:
        """Fill gaps using inpainting"""
        gaps = np.all(panorama == 0, axis=2)
        gap_count = np.sum(gaps)
        
        if gap_count > 0:
            print(f"  Filling {gap_count} gap pixels...", file=sys.stderr)
            gap_mask = gaps.astype(np.uint8) * 255
            panorama = cv2.inpaint(panorama, gap_mask, 10, cv2.INPAINT_TELEA)
        
        return panorama


# =============================================================================
# INTEGRATION FUNCTION
# =============================================================================

def stitch_with_bundle_adjustment(
    photos: List[Dict],
    images: List[np.ndarray],
    depth_maps: List[Optional[np.ndarray]] = None,
    output_width: int = 4096,
    output_height: int = 2048
) -> Tuple[np.ndarray, Optional[np.ndarray], Dict]:
    """
    Main entry point for bundle adjustment stitching.
    
    This implements the full Brown & Lowe 2007 algorithm for
    high-quality automatic panorama stitching.
    """
    stitcher = BundleAdjustmentStitcher(
        output_width=output_width,
        output_height=output_height
    )
    
    return stitcher.stitch(photos, images, depth_maps)


if __name__ == '__main__':
    print("Bundle Adjustment Stitcher (Brown & Lowe 2007)")
    print("Use stitch_with_bundle_adjustment() for high-quality panoramas.")
